"use client";
import React, { useState, useRef, useEffect } from "react";
import styles from "./estimatedetsils.module.css";
import { BarChart2 } from "lucide-react";
import { BsFillChatSquareTextFill } from "react-icons/bs";

// Types for Lead & Estimate Details
interface Person {
  firstName: string;
  lastName: string;
}

interface LeadInfo {
  lead: {
    firstName: string;
    lastName: string;
    countryCode: string;
    phoneNumber: string;
  };
  teamleader: Person;
  generatedBy: Person;
  estID: string;
}

interface FinancialRow {
  id: number;
  title: string;
  amount: string;
}

interface PDFRow {
  id: number;
  finalPrice: string;
  status: string;
}

interface EstimateHistoryDetailsProps {
  estimate: EstimateGenerated | null;
}



const EstimateHistoryDetails: React.FC<EstimateHistoryDetailsProps> = ({ estimate }) => {
  const [showDropdown, setShowDropdown] = useState(false);
  const dropdownRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setShowDropdown(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  if (!estimate) {
    return (
      <div className={styles.nocont}>
        Select a lead to view details
      </div>
    );
  }

  return (
    <div className={styles.sectionContainer} style={{ justifyContent: "center" }}>
      <div className={`${styles.leadHistoryContainer} ${styles.anotherClass}`}>
        <div className={styles.detailsContainer}>
          {/* Left Section */}
          <div className={styles.leftSection} style={{ display: "flex", flexDirection: "column" }}>
            <div className={styles.avatar}>{estimate.lead?.firstName?.charAt(0) ?? ""}</div>
            <div className={styles.name}>{estimate.lead?.firstName} {estimate.lead?.lastName}</div>
            <div className={styles.phone}>{estimate.lead?.countryCode} {estimate.lead?.phoneNumber}</div>

            <div className={styles.optionsContainer} style={{ flexDirection: "column", gap: "2px", paddingTop: "15px" }}>
              <div className={styles.optionsWrapper} ref={dropdownRef}>
                <div
                  className={styles.options}
                  style={{ border: "none", backgroundColor: "rgba(255,255,255,0.05)" }}
                  onClick={() => setShowDropdown(!showDropdown)}
                >
                  <BarChart2 color="#7482ff" />
                </div>
                {showDropdown && (
                  <div className={styles.dropdown}>
                    <div className={styles.dropdownItem}>Give Final Estimate</div>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Middle Section */}
          <div className={styles.middleSection}>
            <p style={{ fontSize: 14, color: "#7482ff", fontWeight: 600 }}>Client Details :</p>
            <p><span className={styles.label}>Estimate ID:</span> <span className={styles.value}>{estimate.estID}</span></p>
            <p><span className={styles.label}>Generated By:</span> <span className={styles.value}>{estimate.generatedBy?.firstName} {estimate.generatedBy?.lastName}</span></p>
            <p><span className={styles.label}>Mobile No:</span> <span className={styles.value}>{estimate.lead?.countryCode} {estimate.lead?.phoneNumber}</span></p>
            <p><span className={styles.label}>Team Leader:</span> <span className={styles.value}>{estimate.generatedBy?.reportingTo?.firstName} {estimate.generatedBy?.reportingTo?.lastName}</span></p>
            <p><span className={styles.label}>Address:</span> <span className={styles.value}>{estimate.lead?.address ?? "NA"}</span></p>
          </div>

          {/* Right Section */}
          <div className={styles.rightSection} style={{ gap: "0.3vh" }}>
            <p style={{ fontSize: 14, color: "#7482ff", fontWeight: 600 }}>Unit Details :</p>
            <p><span className={styles.label}>Project:</span> <span className={styles.value}>{estimate.lead?.project.map((e)=>e.name)}</span></p>
            <p><span className={styles.label}>Configuration:</span> <span className={styles.value}>{estimate.configuration}</span></p>
            <p><span className={styles.label}>Flat no:</span> <span className={styles.value}>{estimate.flatNo}</span></p>
            <p><span className={styles.label}>SS area:</span> <span className={styles.value}>{estimate.ssArea}</span></p>
            <p><span className={styles.label}>Balcony area:</span> <span className={styles.value}>{estimate.balconyArea}</span></p>
            <p><span className={styles.label}>Rera area:</span> <span className={styles.value}>{estimate.reraArea}</span></p>
            <p><span className={styles.label}>Carpet area:</span> <span className={styles.value}>{estimate.carpetArea}</span></p>
          </div>
        </div>

        {/* Financial Price Section */}
        <div style={{ color: "white", fontSize: "20px", fontWeight: 600, padding: "1vw" }} className={styles.sectiontwo}>
          <p className={styles.heading}>Financial Price</p>
          <button className={`${styles.finalbutton} ${styles.optionsbutton}`}>
            <div className={styles.options} style={{ border: "none", backgroundColor: "rgba(255, 255, 255, 0.46)" }}>
              <BsFillChatSquareTextFill color="#eaecffff" />
            </div>
            Get Final Estimate
          </button>
           </div>
          <div className={styles.finalprice}>
            <div className={styles.priceContainer}>
              <h2>Quoting Price</h2>
              <div className={styles.priceGrid}>
    <p className={styles.priceTitle}>📄 Agreement Value</p>
    <p className={styles.priceAmount}>₹ {estimate.agreementValue ?? "NA"}</p>

    <p className={styles.priceTitle}>🏛️ Stamp Duty</p>
    <p className={styles.priceAmount}>₹ {estimate.stampDutyAmount ?? "NA"}</p>

    <p className={styles.priceTitle}>💰 GST Amount</p>
    <p className={styles.priceAmount}>₹ {estimate.gstAmount ?? "NA"}</p>

    <p className={styles.priceTitle}>💵 All-Inclusive</p>
    <p className={styles.priceAmount}>₹ {estimate.allInclusiveValue ?? "NA"}</p>
</div>

            </div>

            {/* PDF Table */}
            <div
           
              className={`${styles.priceContainer} ${styles.pdfcontainer}`}
            >
              <h2 style={{ textAlign: "center", color: "rgb(116,130,255)", marginBottom: "15px", fontSize: "1rem", letterSpacing: "0.5px" }}>
                Estimate PDF
              </h2>
              <table style={{ width: "100%", borderCollapse: "collapse", textAlign: "center" }}>
                <thead>
                  <tr style={{ borderBottom: "1px solid #555" }}>
                    <th style={{ padding: "8px" }}>Sr No.</th>
                    <th style={{ padding: "8px" }}>Final Price</th>
                    <th style={{ padding: "8px" }}>PDF</th>
                    <th style={{ padding: "8px" }}>Status</th>
                  </tr>
                </thead>
              <tbody>
    <tr style={{ borderBottom: "1px solid #555" }}>
        <td style={{ padding: "8px" }}>1</td>
        
        {/* Final Price */}
        <td style={{ padding: "8px" }}>
            ₹ {estimate.finalAgreementValue ?? estimate.agreementValue ?? "NA"}
        </td>

        {/* PDF View Button */}
        <td style={{ padding: "8px" }}>
            {estimate.finalEstDoc ? (
                <a
                    href={estimate.finalEstDoc}
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    <button
                        style={{
                            backgroundColor: "rgb(116,130,255)",
                            color: "white",
                            border: "none",
                            padding: "5px 10px",
                            borderRadius: "8px",
                            cursor: "pointer",
                        }}
                    >
                        View
                    </button>
                </a>
            ) : (
                <span style={{ color: "#999" }}>No PDF</span>
            )}
        </td>

        {/* Status */}
        <td style={{ padding: "8px" }}>
            <button
                style={{
                    backgroundColor: "#0072ff",
                    color: "white",
                    border: "none",
                    padding: "5px 10px",
                    borderRadius: "8px",
                    cursor: "pointer",
                }}
            >
                {estimate.status ?? "Pending"}
            </button>
        </td>
    </tr>
</tbody>

              </table>
           
          </div>

        </div>

      </div>
    </div>
  );
};

export default EstimateHistoryDetails;
