"use client";
import React, { useState, useRef, useEffect } from "react";
import styles from "./estimatedetsils.module.css";
import { BarChart2 } from "lucide-react";
import { BsFillChatSquareTextFill } from "react-icons/bs";

// Types for Lead & Estimate Details
interface Person {
  firstName: string;
  lastName: string;
}

interface LeadInfo {
  lead: {
    firstName: string;
    lastName: string;
    countryCode: string;
    phoneNumber: string;
  };
  teamleader: Person;
  generatedBy: Person;
  estID: string;
}

interface FinancialRow {
  id: number;
  title: string;
  amount: string;
}

interface PDFRow {
  id: number;
  finalPrice: string;
  status: string;
}

interface EstimateHistoryDetailsProps {
  lead: LeadInfo | null;
}

// Dummy data for financial table
const dummyFinancialData: FinancialRow[] = [
  { id: 1, title: "📄 Agreement Value", amount: "₹ 29,99,000" },
  { id: 2, title: "🏛️ Stamp Duty", amount: "₹ 17,77,259" },
  { id: 3, title: "💰 GST Amount", amount: "₹ 14,81,049" },
  { id: 4, title: "💵 All-Inclusive", amount: "₹ 62,57,308" },
];

// Dummy data for PDF table
const dummyPDFData: PDFRow[] = [
  { id: 1, finalPrice: "₹1.5Cr", status: "Pending" },
  { id: 2, finalPrice: "₹2.0Cr", status: "Approved" },
];

const EstimateHistoryDetails: React.FC<EstimateHistoryDetailsProps> = ({ lead }) => {
  const [showDropdown, setShowDropdown] = useState(false);
  const dropdownRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setShowDropdown(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  if (!lead) {
    return (
      <div className={styles.nocont}>
        Select a lead to view details
      </div>
    );
  }

  return (
    <div className={styles.sectionContainer} style={{ justifyContent: "center" }}>
      <div className={`${styles.leadHistoryContainer} ${styles.anotherClass}`}>
        <div className={styles.detailsContainer}>
          {/* Left Section */}
          <div className={styles.leftSection} style={{ display: "flex", flexDirection: "column" }}>
            <div className={styles.avatar}>{lead.lead.firstName.charAt(0)}</div>
            <div className={styles.name}>{lead.lead.firstName} {lead.lead.lastName}</div>
            <div className={styles.phone}>{lead.lead.countryCode} {lead.lead.phoneNumber}</div>

            <div className={styles.optionsContainer} style={{ flexDirection: "column", gap: "2px", paddingTop: "15px" }}>
              <div className={styles.optionsWrapper} ref={dropdownRef}>
                <div
                  className={styles.options}
                  style={{ border: "none", backgroundColor: "rgba(255,255,255,0.05)" }}
                  onClick={() => setShowDropdown(!showDropdown)}
                >
                  <BarChart2 color="#7482ff" />
                </div>
                {showDropdown && (
                  <div className={styles.dropdown}>
                    <div className={styles.dropdownItem}>Give Final Estimate</div>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Middle Section */}
          <div className={styles.middleSection}>
            <p style={{ fontSize: 14, color: "#7482ff", fontWeight: 600 }}>Client Details :</p>
            <p><span className={styles.label}>Estimate ID:</span> <span className={styles.value}>{lead.estID}</span></p>
            <p><span className={styles.label}>Generated By:</span> <span className={styles.value}>{lead.generatedBy.firstName} {lead.generatedBy.lastName}</span></p>
            <p><span className={styles.label}>Mobile No:</span> <span className={styles.value}>{lead.lead.countryCode} {lead.lead.phoneNumber}</span></p>
            <p><span className={styles.label}>Team Leader:</span> <span className={styles.value}>{lead.teamleader.firstName} {lead.teamleader.lastName}</span></p>
            <p><span className={styles.label}>Address:</span> <span className={styles.value}>Vashi</span></p>
          </div>

          {/* Right Section */}
          <div className={styles.rightSection} style={{ gap: "0.3vh" }}>
            <p style={{ fontSize: 14, color: "#7482ff", fontWeight: 600 }}>Unit Details :</p>
            <p><span className={styles.label}>Project:</span> <span className={styles.value}>23 Marina Bay</span></p>
            <p><span className={styles.label}>Configuration:</span> <span className={styles.value}>2BHK</span></p>
            <p><span className={styles.label}>Flat no:</span> <span className={styles.value}>220</span></p>
            <p><span className={styles.label}>SS area:</span> <span className={styles.value}>NA</span></p>
            <p><span className={styles.label}>Balcony area:</span> <span className={styles.value}>NA</span></p>
            <p><span className={styles.label}>Rera area:</span> <span className={styles.value}>NA</span></p>
            <p><span className={styles.label}>Carpet area:</span> <span className={styles.value}>NA</span></p>
          </div>
        </div>

        {/* Financial Price Section */}
        <div style={{ color: "white", fontSize: "20px", fontWeight: 600, padding: "1vw" }} className={styles.sectiontwo}>
          <p className={styles.heading}>Financial Price</p>
          <button className={`${styles.finalbutton} ${styles.optionsbutton}`}>
            <div className={styles.options} style={{ border: "none", backgroundColor: "rgba(255, 255, 255, 0.46)" }}>
              <BsFillChatSquareTextFill color="#eaecffff" />
            </div>
            Get Final Estimate
          </button>
           </div>
          <div className={styles.finalprice}>
            <div className={styles.priceContainer}>
              <h2>Quoting Price</h2>
              <div className={styles.priceGrid}>
                {dummyFinancialData.map(row => (
                  <React.Fragment key={row.id}>
                    <p className={styles.priceTitle}>{row.title}</p>
                    <p className={styles.priceAmount}>{row.amount}</p>
                  </React.Fragment>
                ))}
              </div>
            </div>

            {/* PDF Table */}
            <div
           
              className={`${styles.priceContainer} ${styles.pdfcontainer}`}
            >
              <h2 style={{ textAlign: "center", color: "rgb(116,130,255)", marginBottom: "15px", fontSize: "1rem", letterSpacing: "0.5px" }}>
                Estimate PDF
              </h2>
              <table style={{ width: "100%", borderCollapse: "collapse", textAlign: "center" }}>
                <thead>
                  <tr style={{ borderBottom: "1px solid #555" }}>
                    <th style={{ padding: "8px" }}>Sr No.</th>
                    <th style={{ padding: "8px" }}>Final Price</th>
                    <th style={{ padding: "8px" }}>PDF</th>
                    <th style={{ padding: "8px" }}>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {dummyPDFData.map(row => (
                    <tr key={row.id} style={{ borderBottom: "1px solid #555" }}>
                      <td style={{ padding: "8px" }}>{row.id}</td>
                      <td style={{ padding: "8px" }}>{row.finalPrice}</td>
                      <td style={{ padding: "8px" }}>
                        <button style={{
                          backgroundColor: "rgb(116,130,255)",
                          color: "white",
                          border: "none",
                          padding: "5px 10px",
                          borderRadius: "8px",
                          cursor: "pointer",
                        }}>View</button>
                      </td>
                      <td style={{ padding: "8px" }}>
                        <button style={{
                          backgroundColor: "#0072ff",
                          color: "white",
                          border: "none",
                          padding: "5px 10px",
                          borderRadius: "8px",
                          cursor: "pointer",
                        }}>{row.status}</button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
           
          </div>

        </div>

      </div>
    </div>
  );
};

export default EstimateHistoryDetails;
