export const dummyLeaveData = [

  {
    appliedOn: "2027-05-10",
    employeeName: "Shruti Misal",
    leaveType: "Sick Leave",
    startDate: "2025-05-10",
    endDate: "2025-05-12",
    numberOfDays: 3,
    reason: "Personal reson",
    status: "Pending",
    attachment: "",
  },
  {
    appliedOn: "2027-05-10",
    employeeName: "Shruti Misal",
    leaveType: "Sick Leave",
    startDate: "2025-05-10",
    endDate: "2025-05-12",
    numberOfDays: 3,
    reason: "Personal reson",
    status: "Pending",
    attachment: "",
  },
  {
    appliedOn: "2027-05-10",
    employeeName: "Shruti Misal",
    leaveType: "Sick Leave",
    startDate: "2025-05-10",
    endDate: "2025-05-12",
    numberOfDays: 3,
    reason: "Personal reson",
    status: "Pending",
    attachment: "",
  },
  {
    appliedOn: "2027-05-10",
    employeeName: "Shruti Misal",
    leaveType: "Sick Leave",
    startDate: "2025-05-10",
    endDate: "2025-05-12",
    numberOfDays: 3,
    reason: "Personal reson",
    status: "Pending",
    attachment: "",
  },
  {
    appliedOn: "2027-05-10",
    employeeName: "Dummy One",
    leaveType: "Casual Leave",
    startDate: "2025-05-14",
    endDate: "2025-05-15",
    numberOfDays: 2,
    reason: "Personal reson",
    status: "Rejected",
    attachment: "",
  },
  {
    appliedOn: "2027-05-10",
    employeeName: "Dummy One",
    leaveType: "Casual Leave",
    startDate: "2025-05-14",
    endDate: "2025-05-15",
    numberOfDays: 2,
    reason: "Personal reson",
    status: "Rejected",
    attachment: "",
  },
  {
    appliedOn: "2027-05-10",
    employeeName: "Dummy One",
    leaveType: "Casual Leave",
    startDate: "2025-05-14",
    endDate: "2025-05-15",
    numberOfDays: 2,
    reason: "Personal reson",
    status: "Rejected",
    attachment: "",
  },
  {
    appliedOn: "2027-05-10",
    employeeName: "Dummy One",
    leaveType: "Casual Leave",
    startDate: "2025-05-14",
    endDate: "2025-05-15",
    numberOfDays: 2,
    reason: "Personal reson",
    status: "Rejected",
    attachment: "",
  },
  {
    appliedOn: "2027-05-10",
    employeeName: "Dummy Two",
    leaveType: "Casual Leave",
    startDate: "2025-05-14",
    endDate: "2025-05-15",
    numberOfDays: 2,
    reason: "Personal reson",
    status: "Approved",
    attachment: "",
  },
  {
    appliedOn: "2027-05-10",
    employeeName: "Dummy Two",
    leaveType: "Casual Leave",
    startDate: "2025-05-14",
    endDate: "2025-05-15",
    numberOfDays: 2,
    reason: "Personal reson",
    status: "Approved",
    attachment: "",
  },
  {
    appliedOn: "2027-05-10",
    employeeName: "Dummy Two",
    leaveType: "Casual Leave",
    startDate: "2025-05-14",
    endDate: "2025-05-15",
    numberOfDays: 2,
    reason: "Personal reson",
    status: "Approved",
    attachment: "",
  },
  {
    appliedOn: "2027-05-10",
    employeeName: "Dummy Two",
    leaveType: "Casual Leave",
    startDate: "2025-05-14",
    endDate: "2025-05-15",
    numberOfDays: 2,
    reason: "Personal reson",
    status: "Approved",
    attachment: "",
  },
  {
    appliedOn: "2027-05-10",
    employeeName: "Dummy Two",
    leaveType: "Casual Leave",
    startDate: "2025-05-14",
    endDate: "2025-05-15",
    numberOfDays: 2,
    reason: "Personal reson",
    status: "Approved",
    attachment: "",
  },
];

export const dummyWeekOffData = [
  {
    employeeName: "Shruti Misal",
    appliedOn: "2025-05-10",
    weekoffdate: "2025-05-12",
    reason: "Week Off",
    status: "Pending",
  },
  {
    employeeName: "Dummy One",
    appliedOn: "2025-05-10",
    weekoffdate: "2025-05-12",
    reason: "Week Off",
    status: "Approved",
  },
  {
    employeeName: "Dummy One",
    appliedOn: "2025-05-10",
    weekoffdate: "2025-05-12",
    reason: "Week Off",
    status: "Rejected",
  },
];

export const dummyAssetData = [
  {
    employeeName: "Shruti Misal",
    appliedOn: "2025-05-10",
    assetDate: "2025-05-12",
    assetType: "Mobile",
    remark: "apply to Mobile",
    status: "Pending",
    quantity: "1",
  },

  {
    employeeName: "Shruti Misal",
    appliedOn: "2025-05-10",
    assetDate: "2025-05-12",
    assetType: "Mobile",
    remark: "apply to Mobile",
    status: "Approved",
    quantity: "1",
  },

  {
    employeeName: "Shruti Misal",
    appliedOn: "2025-05-10",
    assetDate: "2025-05-12",
    assetType: "Mobile",
    remark: "apply to Mobile",
    status: "Rejected",
    quantity: "1",
  },
  {
    employeeName: "Shruti Misal",
    appliedOn: "2025-05-10",
    assetDate: "2025-05-12",
    assetType: "Mobile",
    remark: "apply to Mobile",
    status: "Rejected",
    quantity: "1",
  },
];

export const dummyReguData = [
  {
    employeeName: "Shruti Misal",
    appliedOn: "25 April 2025",
    regularizeDate: "6 April 2025",
    checkIn: "NA",
    checkOut: "NA",
    reguType: "WeekOff",
    reason: "for get to apply weekoff",
    status: "Pending",
  },
  {
    employeeName: "Shruti Misal",
    appliedOn: "26 April 2025",
    regularizeDate: "6 April 2025",
    checkIn: "NA",
    checkOut: "NA",
    reguType: "WeekOff",
    reason: "for get to apply weekoff",
    status: "Approved",
  },
  {
    employeeName: "Shruti Misal",
    appliedOn: "27 April 2025",
    regularizeDate: "6 April 2025",
    checkIn: "NA",
    checkOut: "NA",
    reguType: "WeekOff",
    reason: "for get to apply weekoff",
    status: "Rejected",
  },
];

export const dummyReimData = [
  {
    employeeName: "Shruti Misal",
    appliedOn: "25 April 2025",
    reimDate: "29 April 2025",
    reimburseType: "Food",
    amount: "20000",
    approvalBy: "Deepak Karki",
    remark: "Personal reason..",
    attachFile: "",
    attachBillInvoice: "",
    status: "Pending",
  },

  {
    employeeName: "Shruti Misal",
    appliedOn: "25 April 2025",
    reimDate: "25 April 2025",
    reimburseType: "Food",
    amount: "20000",
    approvalBy: "Deepak Karki",
    remark: "Personal reason..",
    attachFile: "",
    attachBillInvoice: "",
    status: "Approved",
  },
  {
    employeeName: "Shruti Misal",
    appliedOn: "25 April 2025",
    reimDate: "24 April 2025",
    reimburseType: "Food",
    amount: "20000",
    approvalBy: "Deepak Karki",
    remark: "Personal reason..",
    attachFile: "",
    attachBillInvoice: "",
    status: "Rejected",
  },
];

export const dummyShiftData = [
  {
    employeeName: "Shruti Misal",
    appliedOn: "25 April 2025",
    shift: "11:00am to 7:00pm",
    shiftrequestdate: "28 April 2025",
    reason: "Personal reason..",
    status: "Pending",
  },

  {
    employeeName: "Shruti Misal",
    appliedOn: "25 April 2025",
    shift: "11:00am to 7:00pm",
    shiftrequestdate: "29 April 2025",
    reason: "Personal reason..",
    status: "Approved",
  },
   {
    employeeName: "Shruti Misal",
    appliedOn: "25 April 2025",
    shift: "11:00am to 7:00pm",
    shiftrequestdate: "30 April 2025",
    reason: "Personal reason..",
    status: "Rejected",
  },
];
